### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rabindra1337** [TheBikramLama/worldlink-package#4]
Are you using epayment worldlink url to get the data?

**Comment by rabindra1337** [comment]
> Are you using epayment worldlink url to get the data?

I mean in the api (https://worldlinkapi.bikramlama.com.np/)
Does the api make a request to epayment site of worldlink?

**Comment by TheBikramLama** [comment]
Yes, the API is getting data from Worldlink's site.

**Comment by rabindra1337** [comment]
So api is web scraping from epayment.worldlink.com.np and then returning  in json format?

**Comment by TheBikramLama** [comment]
Yes.

**Comment by rabindra1337** [comment]
What about the expiry date along with time?
Epayment does not seem to give that info. (It only gives remaining days without including time)

**Comment by TheBikramLama** [comment]
Some of the data are calculated.
